name: CI 03 - System Info in Container

on:
  workflow_dispatch:

jobs:
  system-info-job:
    runs-on: ubuntu-latest

    container:
      image: alpine:3.22

    steps:
      - name: Step 1 - Storage information
        run: lsblk

      - name: Step 2 - Kernel information
        run: uname -a
