name: CI 06 - Build and Test

on:
  workflow_dispatch:

jobs:
  c-lint:
    name: Check C syntax
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run C lint (make lint)
        run: make lint


  pylint:
    name: Python Lint
    runs-on: ubuntu-latest
    needs: c-lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ifaddr psutil pylint

      - name: Run pylint
        run: pylint --disable=missing-docstring script/mysystem/mysystem.py


  python-run:
    name: Python Execution Test
    runs-on: ubuntu-latest
    needs: c-lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ifaddr psutil

      - name: Run Python script
        run: python script/mysystem/mysystem.py
