name: CI 09.1 - C & Python

on:
  push:
    branches:
      - "feature/*"

jobs:
  c-lint:
    name: Lint C code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: make lint

  c-build:
    name: Build C
    runs-on: ubuntu-latest
    needs: c-lint
    steps:
      - uses: actions/checkout@v6
      - run: make build

  c-run:
    name: Run C binary
    runs-on: ubuntu-latest
    needs: c-build
    steps:
      - uses: actions/checkout@v6
      - run: |
          make build
          ./sysinfo

  python-lint:
    name: Lint Python
    runs-on: ubuntu-latest
    needs: c-lint
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: |
          pip install ifaddr psutil pylint
          pylint --disable=missing-docstring script/mysystem/mysystem.py

  python-run:
    name: Run Python script
    runs-on: ubuntu-latest
    needs: python-lint
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: |
          pip install ifaddr psutil
          python script/mysystem/mysystem.py
