name: CI 02 - System Info

on:
  workflow_dispatch:

jobs:
  system-info-job:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Hostname information
        run: hostnamectl

      - name: Step 2 - IPv4 addressing
        run: ip -4 a

      - name: Step 3 - Who am I
        run: who am i
