name: CI 08 - Build and Artifact

on: push

jobs:
  build:
    name: Compile C sources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build C project
        run: make build

      - name: Upload sysinfo binary artifact
        uses: actions/upload-artifact@v5
        with:
          name: sysinfo-binary
          path: ./sysinfo
          if-no-files-found: error
